Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [2]:
import numpy as np

In [3]:
list_ = ['1','2','3','4','5']

In [4]:
array_list = np.array(list_)

In [5]:
print(type(list_))

<class 'list'>


In [6]:
print(type(array_list))

<class 'numpy.ndarray'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list

In [7]:
list_ = ['1','2','3','4','5']

array_list = np.array(list_)

for element in list_:
    print(type(element))
    
    
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both 

the variables, list_ and

arra_list? If so then print the data types of each and every element present in 

both the variables, list_and arra_list.


Yes, there will be a difference in the data type of the elements present in list_ and array_list if array_list is defined as np.array(object=list_, dtype=int).

The dtype=int argument specifies that the resulting NumPy array should have elements of data type int. Since the original list_ contains string elements, they will be converted to int elements during the conversion to a NumPy array.

To print the data types of each and every element present in both list_ and array_list, you can use loops to iterate through each element of the lists and print their data types.

In [9]:
list_ = ['1','2','3','4','5']
array_list = np.array(list_,dtype=int)

for element in list_:
    print(type(element))

for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


# Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape
(ii) size

In [10]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(num_list)

shape = num_array.shape
size = num_array.size

print("Shape:",shape)
print("Size:", size)

Shape: (2, 3)
Size: 6


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [11]:
import numpy as np

In [12]:
zeros_array = np.zeros((3,3))

In [13]:
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [14]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

# Print the matrix
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
